- name: update server and install nginx
  ansible.builtin.apt:
    update_cache: yes
    name: nginx
    # state: present

- name: Remove nginix default conf
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart-nginx

- name: create directory if they don't exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
  loop: "{{ folders_to_create }}"

- name: Copy systemd service file to server
  ansible.builtin.copy:
    src: nginx.conf
    dest: /etc/nginx/conf.d/test.conf
    owner: root
    group: root
  notify: restart-nginx

- name: Create index.html conf
  ansible.builtin.copy:
    src: "{{ item.name }}"
    dest: "/var/www/{{ item.dir }}/{{ item.name }}"
    owner: root
    group: root
  loop: "{{ html_files }}"

# ------ Task that copies file from local files/ folder  to remote host with content   -----------
- name: Copy site configurations
  ansible.builtin.copy:
    src: "{{ item }}/index.html"
    dest: "/var/www/{{ item }}/index.html"
    owner: root
    group: root
  loop: "{{ apps }}"
# Zadatak:
# ansibletest.com/service1 -> /opt/service1/index.html
# ansibletest.com/applicatio1 -> /opt/aplication1/index.html
# ansibletest.com/application2 -> /var/application2/index.html

# teme za istrazivanje "dict", "list" i "list of dicts"
