global:
  scrape_interval: 15s

scrape_configs:
  - job_name: node-exporter
  - job_name: process-exporter
    static_configs:
      - targets: ["localhost:9100", "192.168.1.14:9100", "192.168.1.10:9100"]
